# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20171114_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Testing description input'),
            preserve_default=False,
        ),
    ]
